name = "docushare-lite-dev"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-03"
account_id = "678193e8fde20f230e3d5829c60c4fb3"
[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[site]
bucket = './build'
entry-point = './workers-site'

[env.production]
name = "docushare-lite"
workers_dev = false
route = "docushare.matteopaz.me/*"
zone_id = "f0751e95ee874a4ca5479cd279b7b12b"

